Repository M1ha-Shvn/django-pg-bulk-update, pull requests merged in 2022-02, with the labels that each got.

#83 Switch back to psycopg2 (non-binary) dependency
  requirements.txt
Labels: compatiblity

#86 Issue 83
  Dockerfile
  requirements.txt
Labels: compatiblity

#85 Issue #84
  setup.py
  src/django_pg_bulk_update/clause_operators.py
  src/django_pg_bulk_update/compatibility.py
  src/django_pg_bulk_update/query.py
  src/django_pg_bulk_update/types.py
  tests/fixtures/test_uuid_primary_model.json
  tests/migrations/0004_add_uuid_primary_model.py
  tests/models.py
  tests/test_bulk_create.py
  tests/test_bulk_update.py
  tests/test_bulk_update_or_create.py
Labels: bug

#87 Added django 4.0 to tests in github actions
  .github/workflows/python-tests.yml
Labels: compatiblity

#88 Added ability to add BulkValue() into django expression
  README.md
  setup.py
  src/django_pg_bulk_update/set_functions.py
  tests/test_bulk_create.py
  tests/test_bulk_update.py
  tests/test_bulk_update_or_create.py
Labels: enhancement
